package com.queal.seata.mybatis.dao;

import com.queal.seata.mybatis.model.Goods;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seata_goods
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seata_goods
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seata_goods
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seata_goods
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    Goods selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seata_goods
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seata_goods
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    int updateByPrimaryKey(Goods record);
}