server:
  port: 18081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url:
  #    username:
  #    password:

  cloud:
    nacos:
      discovery:
      # server-addr:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group