spring:
  application:
    name: seata-node1

  profiles:
    active: dev

feign:
  sentinel:
    enabled: true

mybatis:
  mapper.identity: MYSQL
  mapper-locations: classpath:com/queal/seata/mybatis/mapping/*Mapper.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"