package com.queal.seata.mybatis.model;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seata_goods.id
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seata_goods.create_time
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seata_goods.modify_time
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seata_goods.id
     *
     * @return the value of seata_goods.id
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seata_goods.id
     *
     * @param id the value for seata_goods.id
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seata_goods.create_time
     *
     * @return the value of seata_goods.create_time
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seata_goods.create_time
     *
     * @param createTime the value for seata_goods.create_time
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seata_goods.modify_time
     *
     * @return the value of seata_goods.modify_time
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seata_goods.modify_time
     *
     * @param modifyTime the value for seata_goods.modify_time
     *
     * @mbggenerated Thu Aug 29 11:31:44 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}